{
 "title": "GN GST - GNSS Pseudorange Error Statistics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Timestamp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  \"timestamp\"\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ragne RMS",
   "type": "timeseries",
   "description": "RMS value of the standard deviation of the\nranges",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  rms\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Standard Deviation of Semi-Major Axis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  std_dev_major\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Standard Deviationof Semi-Minor Axis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  std_dev_minor\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  orientation\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Standard Deviation of Latitude Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  std_dev_latitude\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Standard Deviation of Latitude Error < 25 m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  std_dev_latitude\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Standard Deviation of Longitude Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  std_dev_longitude\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Standard Deviation of Longitude Error < 25 m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  std_dev_longitude\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Standard Deviation of Altitude Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  std_dev_altitude\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Standard Deviation of Altitude Error < 35 m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  std_dev_altitude\nFROM nmea_gn_gst\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  }
 ]
}