{
 "title": "GN GLL - Geographic Position - Latitude/Longitude",
 "time": { "from": "2021-07-05T23:44:00.000Z", "to": "2021-07-06T00:08:00.000Z" },
 "panels": [
  {
   "title": "Latitude",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  lat AS \"Latitude\"\nFROM nmea_gn_gll\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "type": "dashlist",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 0 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "mag_var_dir" ], "type": "column" }
      ]
     ],
     "table": "nmea_gn_rmc",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  lon AS \"Longitude\"\nFROM nmea_gn_gll\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "type": "dashlist",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "mag_var_dir" ], "type": "column" }
      ]
     ],
     "table": "nmea_gn_rmc",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Latitude Direction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  CASE lat_dir\n    WHEN 'N' THEN 1\n    WHEN 'S' THEN 0\n    ELSE -1\n  END AS \"Latitude Direction\"\nFROM nmea_gn_gll\nWHERE\n  $__timeFilter(datetime)\n  AND lat_dir IS NOT NULL\nORDER BY time"
    }
   ]
  },
  {
   "title": "Latitude Dir Key",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 6 },
   "options": { "content": "1 : North\\\n0 : South" },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Longitude Direction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  CASE lon_dir\n    WHEN 'E' THEN 1\n    WHEN 'W' THEN 0\n    ELSE -1\n  END AS \"Longitude Direction\"\nFROM nmea_gn_gll\nWHERE\n  $__timeFilter(datetime)\n  AND lat_dir IS NOT NULL\nORDER BY time"
    }
   ]
  },
  {
   "title": "Long Dir Key",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "options": { "content": "1 : East\\\n0 : West" },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Data Validity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  CASE status\n    WHEN 'A' THEN 1\n    WHEN 'V' THEN 0\n    ELSE -1\n  END AS \"Validity\"\nFROM nmea_gn_gll\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Position Mode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  CASE faa_mode\n    WHEN 'N' THEN 0\n    WHEN 'E' THEN 1\n    WHEN 'D' THEN 2\n    WHEN 'A' THEN 3\n    ELSE -1\n  END AS \"Position Mode\"\nFROM nmea_gn_gll\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Position Mode Key",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
   "options": {
    "content": "0 : No fix : No Fix / GNSS fix, but user exceeds limits\\\n1 : Estimated/Dead reckoning fix : Dead reckoning fix / Dead reckoning fix but user limits exceeded\\\n2 : Differential GNSS fix : RTK float / RTK fixed / 2D GNSS fix / 3D GNSS fix / Combined GNSS/dead reckoning fix\\\n3 : Autonomous GNSS fix : 2D GNSS fix / 3D GNSS fix / Combined GNSS/dead reckoning fix\\\n\\\n[u-blox 8 / u-blox M8 protocol specification](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_%28UBX-13003221%29.pdf), section 31.1.6"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Timestamp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  timestamp AS \"Timestamp\"\nFROM nmea_gn_gll\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  }
 ]
}