{
 "title": "GN GGA - Global Positioning System Fixed Data",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Quality Indicator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  gps_qual AS \"Quality Indicator\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Quality Indicator Key",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "0 : No fix : No position fix (at power-up after losing satellite lock / GNSS fix but user limits exceeded\\\n1 : Autonomous GNSS fix : 2D GNSS fix / 3D GNSS fix / Combined GNSS/dead reckoning fix\\\n2 : Differential GNSS fix : 2D GNSS fix / 3D GNSS fix / Combined GNSS/dead reckoning fix\\\n4 : RTK fixed\\\n5 : RTK float\\\n6 : Estimated/Dead reckoning fix : Dead reckoning fix/Dead reckoning fix but user limits exceeded\\\n\\\n[u-blox 8 / u-blox M8 protocol specification](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_%28UBX-13003221%29.pdf), section 31.1.6"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Satellites Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  num_sats AS \"Number of Satellites Used\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Horizontal Dilution of Precision",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  horizontal_dil AS \"Horizontal Dilution of Precision\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  altitude AS \"Altitude\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Geoid Separation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  geo_sep AS \"Geoid Separation\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Age of Differential Corrections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  age_gps_data AS \"Age of Differential Corrections\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reference Station ID",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  ref_station_id AS \"Reference Station ID\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Datestamp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  datestamp AS \"Datestamp\"\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Timestamp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  timestamp AS \"Timestamp\"\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  lat AS \"Latitude\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "type": "dashlist",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 50 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "mag_var_dir" ], "type": "column" }
      ]
     ],
     "table": "nmea_gn_rmc",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  lon AS \"Longitude\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "type": "dashlist",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 50 },
   "targets": [
    {
     "select": [
      [
       { "params": [ "mag_var_dir" ], "type": "column" }
      ]
     ],
     "table": "nmea_gn_rmc",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Latitude Direction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  CASE lat_dir\n    WHEN 'N' THEN 1\n    WHEN 'S' THEN 0\n    ELSE -1\n  END AS \"Latitude Direction\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\n  AND lat_dir IS NOT NULL\nORDER BY time"
    }
   ]
  },
  {
   "title": "Latitude Dir Key",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 56 },
   "options": { "content": "1 : North\\\n0 : South" },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Longitude Direction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  CASE lon_dir\n    WHEN 'E' THEN 1\n    WHEN 'W' THEN 0\n    ELSE -1\n  END AS \"Longitude Direction\"\nFROM nmea_gn_gga\nWHERE\n  $__timeFilter(datetime)\n  AND lat_dir IS NOT NULL\nORDER BY time"
    }
   ]
  },
  {
   "title": "Long Dir Key",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 56 },
   "options": { "content": "1 : East\\\n0 : West" },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  }
 ]
}