{
 "title": "GN GSA - GNSS DOP and Active Satellites",
 "time": { "from": "2021-07-05T23:44:00.000Z", "to": "2021-07-06T00:08:00.000Z" },
 "panels": [
  {
   "title": "GPS Space Vehicle IDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  gp_sv_id01 AS \"GPS SV 01 ID\",\n  gp_sv_id02 AS \"GPS SV 02 ID\",\n  gp_sv_id03 AS \"GPS SV 03 ID\",\n  gp_sv_id04 AS \"GPS SV 04 ID\",\n  gp_sv_id05 AS \"GPS SV 05 ID\",\n  gp_sv_id06 AS \"GPS SV 06 ID\",\n  gp_sv_id07 AS \"GPS SV 07 ID\",\n  gp_sv_id08 AS \"GPS SV 08 ID\",\n  gp_sv_id09 AS \"GPS SV 09 ID\",\n  gp_sv_id10 AS \"GPS SV 10 ID\",\n  gp_sv_id11 AS \"GPS SV 11 ID\",\n  gp_sv_id12 AS \"GPS SV 12 ID\"\nFROM nmea_gn_gsa\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "GLONASS Space Vehicle IDs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  gl_sv_id01 AS \"GLONASS SV 01 ID\",\n  gl_sv_id02 AS \"GLONASS SV 02 ID\",\n  gl_sv_id03 AS \"GLONASS SV 03 ID\",\n  gl_sv_id04 AS \"GLONASS SV 04 ID\",\n  gl_sv_id05 AS \"GLONASS SV 05 ID\",\n  gl_sv_id06 AS \"GLONASS SV 06 ID\",\n  gl_sv_id07 AS \"GLONASS SV 07 ID\",\n  gl_sv_id08 AS \"GLONASS SV 08 ID\",\n  gl_sv_id09 AS \"GLONASS SV 09 ID\",\n  gl_sv_id10 AS \"GLONASS SV 10 ID\",\n  gl_sv_id11 AS \"GLONASS SV 11 ID\",\n  gl_sv_id12 AS \"GLONASS SV 12 ID\"\nFROM nmea_gn_gsa\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Dilution of Precision",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  pdop AS \"Position Dilution of Precision\",\n  hdop AS \"Horizontal Dilution of Precision\",\n  vdop AS \"Vertical Dilution of Precision\"\nFROM nmea_gn_gsa\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Navigation Mode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mode_fix_type AS \"Mode Fix Type\"\nFROM nmea_gn_gsa\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Navigation Mode Key",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 24 },
   "options": {
    "content": "1 : No fix : No fix (at power-up after losing satellite lock) / GNSS fix, but user limits exceeded\\\n2 : 2D fix : Dead reckoning fix / Dead reckoning fix but user limits exceeded / 2D GNSS fix\\\n3 : 3D fix : 3D GNSS fix / Combined GNSS/dead reckoning fix\\\n\\\n[u-blox 8 / u-blox M8 protocol specification](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_%28UBX-13003221%29.pdf), section 31.1.6"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Operation Mode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  CASE mode\n    WHEN 'A' THEN 1\n    WHEN 'M' THEN 0\n    ELSE -1\n  END AS \"Operation Mode\"\nFROM nmea_gn_gsa\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Operation Mode Key",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 30 },
   "options": {
    "content": "0 : Manually set to operate in 2D or 3D mode\\\n1 : Automatically switching between 2D or 3D mode\\\n\\\n[u-blox 8 / u-blox M8 protocol specification](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_%28UBX-13003221%29.pdf), section 31.2.11"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  }
 ]
}