{
 "title": "GN VTG - Course of Ground and Ground Speed",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Course Over Ground",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  true_track AS \"True Course Over Ground\",\n  mag_track  AS \"Magnetic Course Over Ground\"\nFROM nmea_gn_vtg\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Speed Over Ground",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "yaxes": [
    { "format": "velocityknot" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  spd_over_grnd_kts  AS \"Speed Over Ground (Knots)\",\n  spd_over_grnd_kmph AS \"Speed Over Ground (kph)\"\nFROM nmea_gn_vtg\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Position Mode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  CASE faa_mode\n    WHEN 'N' THEN 0\n    WHEN 'E' THEN 1\n    WHEN 'D' THEN 2\n    WHEN 'A' THEN 3\n    ELSE -1\n  END AS \"Position Mode\"\nFROM nmea_gn_vtg\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Position Mode Key",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 17 },
   "options": {
    "content": "0 : No fix : No Fix / GNSS fix, but user exceeds limits\\\n1 : Estimated/Dead reckoning fix : Dead reckoning fix / Dead reckoning fix but user limits exceeded\\\n2 : Differential GNSS fix : RTK float / RTK fixed / 2D GNSS fix / 3D GNSS fix / Combined GNSS/dead reckoning fix\\\n3 : Autonomous GNSS fix : 2D GNSS fix / 3D GNSS fix / Combined GNSS/dead reckoning fix\\\n\\\nper [u-blox 8 / u-blox M8 protocol specification](https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_%28UBX-13003221%29.pdf), section 31.1.6"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  mag_var_dir\nFROM nmea_gn_rmc\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  }
 ]
}