{
 "title": "GP/GL GSV - GNSS Satellites in View",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Number of Space Vehicles in View",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  num_sv_in_view AS \"GPS\"\nFROM nmea_gp_gsv\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  num_sv_in_view AS \"GLONASS\"\nFROM nmea_gl_gsv\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Space Vehicle Signal to Noise Ratios",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  snr_1  AS \"GPS SV  1 SNR\",\n  snr_2  AS \"GPS SV  2 SNR\",\n  snr_3  AS \"GPS SV  3 SNR\",\n  snr_4  AS \"GPS SV  4 SNR\",\n  snr_5  AS \"GPS SV  5 SNR\",\n  snr_6  AS \"GPS SV  6 SNR\",\n  snr_7  AS \"GPS SV  7 SNR\",\n  snr_8  AS \"GPS SV  8 SNR\",\n  snr_9  AS \"GPS SV  9 SNR\",\n  snr_10 AS \"GPS SV 10 SNR\",\n  snr_11 AS \"GPS SV 11 SNR\",\n  snr_12 AS \"GPS SV 12 SNR\",\n  snr_13 AS \"GPS SV 13 SNR\",\n  snr_14 AS \"GPS SV 14 SNR\",\n  snr_15 AS \"GPS SV 15 SNR\",\n  snr_16 AS \"GPS SV 16 SNR\"\nFROM nmea_gp_gsv\nWHERE\n  $__timeFilter(datetime)\n  AND snr_1 IS NOT NULL\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  snr_1  AS \"GLONASS SV  1 SNR\",\n  snr_2  AS \"GLONASS SV  2 SNR\",\n  snr_3  AS \"GLONASS SV  3 SNR\",\n  snr_4  AS \"GLONASS SV  4 SNR\",\n  snr_5  AS \"GLONASS SV  5 SNR\",\n  snr_6  AS \"GLONASS SV  6 SNR\",\n  snr_7  AS \"GLONASS SV  7 SNR\",\n  snr_8  AS \"GLONASS SV  8 SNR\",\n  snr_9  AS \"GLONASS SV  9 SNR\",\n  snr_10 AS \"GLONASS SV 10 SNR\",\n  snr_11 AS \"GLONASS SV 11 SNR\",\n  snr_12 AS \"GLONASS SV 12 SNR\",\n  snr_13 AS \"GLONASS SV 13 SNR\",\n  snr_14 AS \"GLONASS SV 14 SNR\",\n  snr_15 AS \"GLONASS SV 15 SNR\",\n  snr_16 AS \"GLONASS SV 16 SNR\"\nFROM nmea_gl_gsv\nWHERE\n  $__timeFilter(datetime)\n  AND snr_1 IS NOT NULL\nORDER BY time"
    }
   ]
  },
  {
   "title": "Space Vehicle Elevations",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  elevation_deg_1  AS \"GPS SV  1 Elevation\",\n  elevation_deg_2  AS \"GPS SV  2 Elevation\",\n  elevation_deg_3  AS \"GPS SV  3 Elevation\",\n  elevation_deg_4  AS \"GPS SV  4 Elevation\",\n  elevation_deg_5  AS \"GPS SV  5 Elevation\",\n  elevation_deg_6  AS \"GPS SV  6 Elevation\",\n  elevation_deg_7  AS \"GPS SV  7 Elevation\",\n  elevation_deg_8  AS \"GPS SV  8 Elevation\",\n  elevation_deg_9  AS \"GPS SV  9 Elevation\",\n  elevation_deg_10 AS \"GPS SV 10 Elevation\",\n  elevation_deg_11 AS \"GPS SV 11 Elevation\",\n  elevation_deg_12 AS \"GPS SV 12 Elevation\",\n  elevation_deg_13 AS \"GPS SV 13 Elevation\",\n  elevation_deg_14 AS \"GPS SV 14 Elevation\",\n  elevation_deg_15 AS \"GPS SV 15 Elevation\",\n  elevation_deg_16 AS \"GPS SV 16 Elevation\"\nFROM nmea_gp_gsv\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  elevation_deg_1  AS \"GLONASS SV  1 Elevation\",\n  elevation_deg_2  AS \"GLONASS SV  2 Elevation\",\n  elevation_deg_3  AS \"GLONASS SV  3 Elevation\",\n  elevation_deg_4  AS \"GLONASS SV  4 Elevation\",\n  elevation_deg_5  AS \"GLONASS SV  5 Elevation\",\n  elevation_deg_6  AS \"GLONASS SV  6 Elevation\",\n  elevation_deg_7  AS \"GLONASS SV  7 Elevation\",\n  elevation_deg_8  AS \"GLONASS SV  8 Elevation\",\n  elevation_deg_9  AS \"GLONASS SV  9 Elevation\",\n  elevation_deg_10 AS \"GLONASS SV 10 Elevation\",\n  elevation_deg_11 AS \"GLONASS SV 11 Elevation\",\n  elevation_deg_12 AS \"GLONASS SV 12 Elevation\",\n  elevation_deg_13 AS \"GLONASS SV 13 Elevation\",\n  elevation_deg_14 AS \"GLONASS SV 14 Elevation\",\n  elevation_deg_15 AS \"GLONASS SV 15 Elevation\",\n  elevation_deg_16 AS \"GLONASS SV 16 Elevation\"\nFROM nmea_gl_gsv\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Space Vehicle Azimuths",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  azimuth_1  AS \"GPS SV  1 Azimuth\",\n  azimuth_2  AS \"GPS SV  2 Azimuth\",\n  azimuth_3  AS \"GPS SV  3 Azimuth\",\n  azimuth_4  AS \"GPS SV  4 Azimuth\",\n  azimuth_5  AS \"GPS SV  5 Azimuth\",\n  azimuth_6  AS \"GPS SV  6 Azimuth\",\n  azimuth_7  AS \"GPS SV  7 Azimuth\",\n  azimuth_8  AS \"GPS SV  8 Azimuth\",\n  azimuth_9  AS \"GPS SV  9 Azimuth\",\n  azimuth_10 AS \"GPS SV 10 Azimuth\",\n  azimuth_11 AS \"GPS SV 11 Azimuth\",\n  azimuth_12 AS \"GPS SV 12 Azimuth\",\n  azimuth_13 AS \"GPS SV 13 Azimuth\",\n  azimuth_14 AS \"GPS SV 14 Azimuth\",\n  azimuth_15 AS \"GPS SV 15 Azimuth\",\n  azimuth_16 AS \"GPS SV 16 Azimuth\"\nFROM nmea_gp_gsv\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  azimuth_1  AS \"GLONASS SV  1 Azimuth\",\n  azimuth_2  AS \"GLONASS SV  2 Azimuth\",\n  azimuth_3  AS \"GLONASS SV  3 Azimuth\",\n  azimuth_4  AS \"GLONASS SV  4 Azimuth\",\n  azimuth_5  AS \"GLONASS SV  5 Azimuth\",\n  azimuth_6  AS \"GLONASS SV  6 Azimuth\",\n  azimuth_7  AS \"GLONASS SV  7 Azimuth\",\n  azimuth_8  AS \"GLONASS SV  8 Azimuth\",\n  azimuth_9  AS \"GLONASS SV  9 Azimuth\",\n  azimuth_10 AS \"GLONASS SV 10 Azimuth\",\n  azimuth_11 AS \"GLONASS SV 11 Azimuth\",\n  azimuth_12 AS \"GLONASS SV 12 Azimuth\",\n  azimuth_13 AS \"GLONASS SV 13 Azimuth\",\n  azimuth_14 AS \"GLONASS SV 14 Azimuth\",\n  azimuth_15 AS \"GLONASS SV 15 Azimuth\",\n  azimuth_16 AS \"GLONASS SV 16 Azimuth\"\nFROM nmea_gl_gsv\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Space Vehicle Pseudorandom Noise Codes",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  sv_prn_num_1  AS \"GPS SV  1 PRN\",\n  sv_prn_num_2  AS \"GPS SV  2 PRN\",\n  sv_prn_num_3  AS \"GPS SV  3 PRN\",\n  sv_prn_num_4  AS \"GPS SV  4 PRN\",\n  sv_prn_num_5  AS \"GPS SV  5 PRN\",\n  sv_prn_num_6  AS \"GPS SV  6 PRN\",\n  sv_prn_num_7  AS \"GPS SV  7 PRN\",\n  sv_prn_num_8  AS \"GPS SV  8 PRN\",\n  sv_prn_num_9  AS \"GPS SV  9 PRN\",\n  sv_prn_num_10 AS \"GPS SV 10 PRN\",\n  sv_prn_num_11 AS \"GPS SV 11 PRN\",\n  sv_prn_num_12 AS \"GPS SV 12 PRN\",\n  sv_prn_num_13 AS \"GPS SV 13 PRN\",\n  sv_prn_num_14 AS \"GPS SV 14 PRN\",\n  sv_prn_num_15 AS \"GPS SV 15 PRN\",\n  sv_prn_num_16 AS \"GPS SV 16 PRN\"\nFROM nmea_gp_gsv\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  sv_prn_num_1  AS \"GLONASS SV  1 PRN\",\n  sv_prn_num_2  AS \"GLONASS SV  2 PRN\",\n  sv_prn_num_3  AS \"GLONASS SV  3 PRN\",\n  sv_prn_num_4  AS \"GLONASS SV  4 PRN\",\n  sv_prn_num_5  AS \"GLONASS SV  5 PRN\",\n  sv_prn_num_6  AS \"GLONASS SV  6 PRN\",\n  sv_prn_num_7  AS \"GLONASS SV  7 PRN\",\n  sv_prn_num_8  AS \"GLONASS SV  8 PRN\",\n  sv_prn_num_9  AS \"GLONASS SV  9 PRN\",\n  sv_prn_num_10 AS \"GLONASS SV 10 PRN\",\n  sv_prn_num_11 AS \"GLONASS SV 11 PRN\",\n  sv_prn_num_12 AS \"GLONASS SV 12 PRN\",\n  sv_prn_num_13 AS \"GLONASS SV 13 PRN\",\n  sv_prn_num_14 AS \"GLONASS SV 14 PRN\",\n  sv_prn_num_15 AS \"GLONASS SV 15 PRN\",\n  sv_prn_num_16 AS \"GLONASS SV 16 PRN\"\nFROM nmea_gl_gsv\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    }
   ]
  }
 ]
}